/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_com_medidor_temperatura_jni_RecuperaDadosJNI */

#ifndef _Included_br_com_medidor_temperatura_jni_RecuperaDadosJNI
#define _Included_br_com_medidor_temperatura_jni_RecuperaDadosJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_com_medidor_temperatura_jni_RecuperaDadosJNI
 * Method:    temperatura
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_com_medidor_temperatura_jni_RecuperaDadosJNI_temperatura
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
