/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SuperGerenciadorPing.java
 *
 * Created on 05/03/2012, 17:07:36
 */
package denis.ping.service.view;

import java.awt.AWTException;
import java.awt.Image;
import java.awt.SystemTray;
import java.awt.TrayIcon;
import java.net.InetAddress;
import java.net.UnknownHostException;
import javax.swing.ImageIcon;
import denis.ping.service.PingService;
import denis.ping.service.bean.BeanConfig;
import denis.ping.service.constants.EnumConst;
import denis.ping.service.controller.PingController;
import denis.ping.service.view.pop.PopUpIcon;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Tela gerenciadora
 * @author Denis Soares Moreira
 */
public final class SuperGerenciadorPing extends javax.swing.JFrame {

    private static final String CARREGANDOGIF = "/carregando.gif";
    private static final String FONTE_WICKENDEN_CAFE_NDP = "Wickenden Cafe NDP";
    private static final String ICO_DOWNPNG = "/ico_down.png";
    private static final String ICO_UPPNG = "/ico_up.png";
    private static final String NÃO_FOI_POSSIVEL_CONECTAR_A_VPN = "N\u00e3o foi possivel conectar a VPN.";
    private static final String ONLINE = "Online";
    private static final String PROCESSANDO_VERIFICAÇÃO_DE_REDE = "Processando verifica\u00e7\u00e3o de rede.";
    private static final String PROCESSO_DE_VERIFICAÇÃO_PARADO = "Processo de verifica\u00e7\u00e3o parado.";
    private static final String PROCESSO_DE_VERIFICAÇÃO_PODE_AINDA_ESTAR_S = "Processo de verifica\u00e7\u00e3o pode ainda estar sendo processado.";
    private static final String SISTEMA_MINIMIZADO = "Sistema minimizado";
    private static final String SISTEMA_PAUSADO = "Sistema pausado";
    private static final String SISTEMA_STARTADO = "Sistema startado";
    private static final String STATUS_VPN = "Status VPN";
    private static final String VAZIO = "";
    private static final String VERIFICANDO = "verificando....";
    private static final String WICKENDEN_CAFE_NDP = "Wickenden Cafe NDP";
    private static final String BYTES_TEMPO_TTL = "Bytes  | Tempo  | TTL";
    private static final String _BYTES_ = "Bytes ";
    private static final String OFFLINE = "Offline";
    private static final String _TEMPO_ = " | Tempo ";
    private static final String _TTL_ = " | TTL ";
    private  DefaultTableModel moldelTable = null;
    private int LinhaSelecionada = 0;
    private PingController ping = null;
    private final PopUpIcon popup = new PopUpIcon(this);
    private BeanConfig bean = new BeanConfig();
    private SystemTray tray = SystemTray.getSystemTray();
    private final Image imageIcon = new ImageIcon((this.getClass().getClassLoader().getResource("ico_down.png"))).getImage();
    private final Image imageIconOn = new ImageIcon((this.getClass().getClassLoader().getResource("ico_up.png"))).getImage();
    private final Image imgIco = new ImageIcon((this.getClass().getClassLoader().getResource("pingmv.png"))).getImage();
    public  final TrayIcon trayIcon = new TrayIcon(imageIcon, "Ping da Migração", popup);
    private final PingService service = new PingService(bean);
    private int nMinErros = 0;

    /** Creates new form SuperGerenciadorPing **/
    public SuperGerenciadorPing() {
        initComponents();

        try {
            addTray();
            IPUser.setText(InetAddress.getLocalHost().getHostAddress());
            HostName.setText(InetAddress.getLocalHost().getHostName());
        } catch (UnknownHostException ex) {
            System.out.println(ex.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HostName = new javax.swing.JTextField();
        IPUser = new javax.swing.JTextField();
        start = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        carregando1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        timeView = new javax.swing.JTextField();
        hostView = new javax.swing.JTextField();
        pingView = new javax.swing.JTextField();
        carregando = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        status = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setTitle("PingMig 2.0");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(imgIco);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 1, 12)))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel1.setText("IP User:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 60, 80, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel2.setText("Maquina:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 30, 80, 20);

        HostName.setEditable(false);
        HostName.setFont(new java.awt.Font("Tahoma", 1, 11));
        HostName.setForeground(new java.awt.Color(51, 51, 51));
        HostName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HostName.setToolTipText("Nome da maquina do user");
        jPanel1.add(HostName);
        HostName.setBounds(80, 30, 140, 20);

        IPUser.setEditable(false);
        IPUser.setFont(new java.awt.Font("Tahoma", 1, 11));
        IPUser.setForeground(new java.awt.Color(51, 51, 51));
        IPUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IPUser.setToolTipText("Numero do IP do user");
        jPanel1.add(IPUser);
        IPUser.setBounds(80, 60, 140, 20);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(10, 50, 240, 110);

        start.setFont(new java.awt.Font("Tahoma", 1, 11));
        start.setText("Conectar");
        start.setToolTipText("Conectar");
        start.setContentAreaFilled(false);
        start.setFocusable(false);
        start.setRequestFocusEnabled(false);
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        jPanel4.add(start);
        start.setBounds(10, 10, 90, 33);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton2.setText("Minimizar");
        jButton2.setToolTipText("Minimizar");
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(210, 10, 90, 33);

        stop.setFont(new java.awt.Font("Tahoma", 1, 11));
        stop.setText("Stop");
        stop.setToolTipText("Stop");
        stop.setContentAreaFilled(false);
        stop.setFocusable(false);
        stop.setRequestFocusEnabled(false);
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        jPanel4.add(stop);
        stop.setBounds(110, 10, 90, 33);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Ping", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 1, 12)))); // NOI18N
        jPanel5.setLayout(null);

        carregando1.setFont(new java.awt.Font("Wickenden Cafe NDP", 1, 8));
        carregando1.setForeground(new java.awt.Color(0, 102, 153));
        carregando1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carregando1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(carregando1);
        carregando1.setBounds(360, 120, 60, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Host a conectar", "Timeout", "Status"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 480, 260);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(440, 50, 500, 290);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Ping", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 1, 12)))); // NOI18N
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel4.setText("Time out:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 60, 80, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel5.setText("Ping:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 90, 80, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel6.setText("Host a conectar:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 30, 80, 20);

        timeView.setFont(new java.awt.Font("Tahoma", 1, 11));
        timeView.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        timeView.setText("1000");
        timeView.setToolTipText("Time out");
        jPanel2.add(timeView);
        timeView.setBounds(110, 60, 290, 20);

        hostView.setFont(new java.awt.Font("Tahoma", 1, 11));
        hostView.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hostView.setText("172.16.40.2");
        hostView.setToolTipText("Host a conectar");
        hostView.setOpaque(false);
        hostView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostViewActionPerformed(evt);
            }
        });
        jPanel2.add(hostView);
        hostView.setBounds(110, 30, 290, 20);

        pingView.setEditable(false);
        pingView.setFont(new java.awt.Font("Tahoma", 1, 11));
        pingView.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pingView.setToolTipText("Ping");
        jPanel2.add(pingView);
        pingView.setBounds(110, 90, 290, 20);

        carregando.setFont(new java.awt.Font("Wickenden Cafe NDP", 1, 8));
        carregando.setForeground(new java.awt.Color(0, 102, 153));
        carregando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carregando.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(carregando);
        carregando.setBounds(360, 120, 60, 30);

        jLabel3.setFont(new java.awt.Font("Segoe Script", 3, 14));
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Denis Soares Moreira");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(110, 150, 170, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel7.setText("Desenvolvido por:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 150, 100, 20);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(10, 160, 430, 180);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 1, 12)))); // NOI18N
        jPanel3.setLayout(null);

        status.setFont(new java.awt.Font("Wickenden Cafe NDP", 1, 24));
        status.setForeground(new java.awt.Color(204, 51, 0));
        status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico_down.png"))); // NOI18N
        status.setText("Offline");
        jPanel3.add(status);
        status.setBounds(40, 40, 140, 30);

        jPanel4.add(jPanel3);
        jPanel3.setBounds(250, 50, 190, 110);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton4.setText("Parar Todos");
        jButton4.setToolTipText("Minimizar");
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusable(false);
        jButton4.setRequestFocusEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(830, 10, 110, 33);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 960, 350);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-963)/2, (screenSize.height-382)/2, 963, 382);
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed

        start.setEnabled(false);
        stop.setEnabled(true);
        carregando.setIcon(new ImageIcon(getClass().getResource(CARREGANDOGIF)));
        carregando.setText(VERIFICANDO);
        ping = new PingController(this, service.startConfig(timeView.getText(), hostView.getText()));
        ping.start();
        trayIcon.displayMessage(SISTEMA_STARTADO, PROCESSANDO_VERIFICAÇÃO_DE_REDE, TrayIcon.MessageType.INFO);

        // this.setVisible(false);
    }//GEN-LAST:event_startActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        ping.interrupt();
        ping.stop();
        carregando.setIcon(null);
        carregando.setText(VAZIO);
        status.setFont(new java.awt.Font(WICKENDEN_CAFE_NDP, 1, 24));
        status.setForeground(new java.awt.Color(204, 51, 0));
        status.setIcon(new ImageIcon(getClass().getResource(ICO_DOWNPNG)));
        status.setText(OFFLINE);
        trayIcon.displayMessage(SISTEMA_PAUSADO, PROCESSO_DE_VERIFICAÇÃO_PARADO, TrayIcon.MessageType.INFO);
        start.setEnabled(true);
        stop.setEnabled(false);
        trayIcon.setImage(imageIcon);
        alterarStattusTable( new BeanConfig() );
    }//GEN-LAST:event_stopActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        trayIcon.displayMessage(SISTEMA_MINIMIZADO, PROCESSO_DE_VERIFICAÇÃO_PODE_AINDA_ESTAR_S, TrayIcon.MessageType.INFO);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void hostViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hostViewActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HostName;
    private javax.swing.JTextField IPUser;
    private static javax.swing.JLabel carregando;
    private static javax.swing.JLabel carregando1;
    private javax.swing.JTextField hostView;
    private static javax.swing.JButton jButton2;
    private static javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pingView;
    private static javax.swing.JButton start;
    private static javax.swing.JLabel status;
    private static javax.swing.JButton stop;
    private javax.swing.JTextField timeView;
    // End of variables declaration//GEN-END:variables

    /**
     * Verifica se o status e conta o erro e muda o status
     * @param varStat boolean
     * @param bytes bytes
     * @param tempo tempo
     * @param ttl ttl
     */
    public final void alteraStatus(boolean varStat, String bytes, String tempo, String ttl , BeanConfig beanConf) {

        if (varStat) {
            beanConf.setStattus("Online");
            preencherDadosTable(beanConf);
       
            pingView.setText(_BYTES_ + bytes + _TEMPO_ + tempo + _TTL_ + ttl);
            start.setEnabled(false);
            carregando.setIcon(new ImageIcon(getClass().getResource(CARREGANDOGIF)));
            carregando.setText(VERIFICANDO);
            status.setFont(new java.awt.Font(WICKENDEN_CAFE_NDP, 1, 24));
            status.setForeground(new java.awt.Color(102, 204, 0));
            status.setIcon(new ImageIcon(getClass().getResource(ICO_UPPNG)));
            status.setText(ONLINE);
            trayIcon.getImage();
            start.setEnabled(false);
            stop.setEnabled(true);
            trayIcon.setImage(imageIconOn);
            nMinErros = 0;
            
        } else {
            nMinErros++;
            if (nMinErros >= EnumConst.NOVE.val()) {

                if (nMinErros <= EnumConst.NOVE.val()) {
                    trayIcon.displayMessage(STATUS_VPN,NÃO_FOI_POSSIVEL_CONECTAR_A_VPN,
                            TrayIcon.MessageType.ERROR);
                }
                beanConf.setStattus("Offline");
                preencherDadosTable(beanConf);
                pingView.setText(BYTES_TEMPO_TTL);
                status.setFont(new java.awt.Font(FONTE_WICKENDEN_CAFE_NDP, 1, 24));
                status.setForeground(new java.awt.Color(204, 51, 0));
                status.setText(OFFLINE);
                trayIcon.setImage(imageIcon);
                status.setIcon(new ImageIcon(getClass().getResource(ICO_DOWNPNG)));

            }
        }

    }

    public final void addTray() {
        try {
            trayIcon.setImageAutoSize(true);
            tray.add(trayIcon);
        } catch (AWTException e) {
            System.out.println(e.getMessage());
        }
    }

     public int preencherDadosTable(BeanConfig config){
         if(config.getId() == 0){
         moldelTable = (DefaultTableModel) jTable1.getModel();
         moldelTable.setNumRows(0);
         moldelTable.addRow(new Object[]{config.getHostVpn(), config.getTimeOut(), config.getStattus()});
         config.setId(moldelTable.getRowCount());
         LinhaSelecionada = config.getId();
         return moldelTable.getRowCount();
         
         }else{
             alterarStattusTable(config);
         }
         
       return moldelTable.getRowCount();
      
   }
     
   public void alterarStattusTable(BeanConfig config){
   
           moldelTable.setValueAt(config.getHostVpn(), config.getId(), 0);
           moldelTable.setValueAt(config.getTimeOut(), config.getId(), 1);
           moldelTable.setValueAt(config.getStattus(), config.getId(), 2);

   }
}
