package web.bean.canonico;
// default package
// Generated 11/05/2012 16:07:38 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * Tcanal generated by hbm2java
 */
public class Canal implements Serializable {

    private static final long serialVersionUID = 4592504945647975142L;
    private Long codigo;
	private TipoCanal tipoCanal;
	private String descricaoCanal;
	private String codigoExterno;


	public Canal() {
	    
	}


    /**
     * @return the codigo
     */
    public Long getCodigo() {
        return codigo;
    }


    /**
     * @param codigo the codigo to set
     */
    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }


    /**
     * @return the tipoCanal
     */
    public TipoCanal getTipoCanal() {
        return tipoCanal;
    }


    /**
     * @param tipoCanal the tipoCanal to set
     */
    public void setTipoCanal(TipoCanal tipoCanal) {
        this.tipoCanal = tipoCanal;
    }


    /**
     * @return the descricaoCanal
     */
    public String getDescricaoCanal() {
        return descricaoCanal;
    }


    /**
     * @param descricaoCanal the descricaoCanal to set
     */
    public void setDescricaoCanal(String descricaoCanal) {
        this.descricaoCanal = descricaoCanal;
    }


    /**
     * @return the codigoExterno
     */
    public String getCodigoExterno() {
        return codigoExterno;
    }


    /**
     * @param codigoExterno the codigoExterno to set
     */
    public void setCodigoExterno(String codigoExterno) {
        this.codigoExterno = codigoExterno;
    }

}
